// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ConsoleApp.Data.Configurations;
using ConsoleApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable disable

namespace ConsoleApp.Data
{
    public partial class MagicSwitchBoardContext : DbContext
    {
        public MagicSwitchBoardContext()
        {
        }

        public MagicSwitchBoardContext(DbContextOptions<MagicSwitchBoardContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Configuration> Configuration { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=Magic.Switch.Board;Integrated Security=true");

            modelBuilder.ApplyConfiguration(new Configurations.ConfigurationConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
