// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp.Models
{
    [Table("Configuration", Schema = "private")]
    public partial class Configuration
    {
        [Key]
        public Guid ConfigurationId { get; set; }
        [Required]
        [Column(TypeName = "xml")]
        public string XmlData { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime ValidTill { get; set; }
    }
}