CREATE TABLE [private].[Person] (
	[PersonId] INT NOT NULL IDENTITY CONSTRAINT [PK_Person] PRIMARY KEY NONCLUSTERED
	, [FirstName] NVARCHAR(50) NOT NULL
	, [MiddleName] NVARCHAR(50) NULL
	, [LastName] NVARCHAR(50) NOT NULL
	, [ValidFrom] datetime2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
	, [ValidTo] datetime2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
	, PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
	)
	WITH (
		MEMORY_OPTIMIZED = ON,
    DURABILITY = SCHEMA_AND_DATA,
		SYSTEM_VERSIONING = ON (HISTORY_TABLE = [history].[Person])
		);